github_login:
  path: /login/check-github

hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect_41.xml"
  prefix:   /connect

hwi_oauth_connect:
  resource: "@HWIOAuthBundle/Resources/config/routing/connect_41.xml"
  prefix:   /connect

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
